### PR TITLE
Hello World Test

### PR DESCRIPTION
**Pull request by ntestman**

### CODE REVIEW

**Comment by nkleffman** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Validation/2/
Test FAILed.

**Comment by ntestman** [comment]
retest this please

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/3/
Test PASSed.

**Comment by nkleffman** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Validation/3/
Test FAILed.

**Pull request merged**
