### PR TITLE
Test triggered deploy

### PR DESCRIPTION
**Pull request by nkleffman**

### CODE REVIEW

**Comment by nkleffman** [comment]
## Build comment file: 

## Validation Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Validation/5/
Test PASSed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/2/
Test FAILed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/3/
Test PASSed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/4/
Test PASSed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/5/
Test FAILed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
!!! Couldn't read commit file !!!

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/6/
Test FAILed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

The user null try to validate
      A553276 The pull request can't be deployed verify your code, if you think that
      your code is OK and the error is for data, credentials or any external issue, please notify the error and when
      it is solved create a comment with the content 'retest this please'.
      groovy.lang.MissingPropertyException: No such property: $properties for class: embedded_script_in_C__Users_nathan_dot_j_dot_kleffman_git_SFDC_Local_Deploy_build_dot_xml
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
    at embedded_script_in_C__Users_nathan_dot_j_dot_kleffman_git_SFDC_Local_Deploy_build_dot_xml.run(embedded_script_in_C__Users_nathan_dot_j_dot_kleffman_git_SFDC_Local_Deploy_build_dot_xml:19)
    at org.codehaus.groovy.ant.Groovy.parseAndRunScript(Groovy.java:497)
    at org.codehaus.groovy.ant.Groovy.execGroovy(Groovy.java:444)
    at org.codehaus.groovy.ant.Groovy.execute(Groovy.java:309)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

---

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/7/
Test FAILed.

**Comment by VictorCabello** [comment]
good looks like it works, please send me your current build.xml

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/1/
Test FAILed.

**Comment by nkleffman** [comment]
deploy this

**Comment by nkleffman** [comment]
## Build comment file: 

## Deployment Successful

Refer to this link for build results (access rights to CI server needed): 
http://localhost:8080/job/Pull_Request_Deploy/2/
Test FAILed.

**Pull request merged**
